import mongoose from "mongoose";

const userIds = [
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
];

export const users = [
  {
    _id: userIds[0],
    firstName: "Олександр",
    lastName: "Петренко",
    email: "oleksandr.petrenko@gmail.com",
    password: "$2b$10$dsasdgsagasda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p11.jpeg",
    friends: [],
    location: "Київ, Україна",
    occupation: "Розробник програмного забезпечення",
    viewedProfile: 14561,
    impressions: 888822,
    createdAt: 1115211422,
    updatedAt: 1115211422,
    __v: 0,
  },
  {
    _id: userIds[1],
    firstName: "Марія",
    lastName: "Коваленко",
    email: "maria.kovalenko@gmail.com",
    password: "$!FEAS@!O)_IDJda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p3.jpeg",
    friends: [],
    location: "Львів, Україна",
    occupation: "UX/UI Дизайнер",
    viewedProfile: 12351,
    impressions: 55555,
    createdAt: 1595589072,
    updatedAt: 1595589072,
    __v: 0,
  },
  {
    _id: userIds[2],
    firstName: "Андрій",
    lastName: "Мельник",
    email: "andriy.melnyk@gmail.com",
    password: "da39a3ee5e6b4b0d3255bfef95601890afd80709",
    picturePath: "p4.jpeg",
    friends: [],
    location: "Харків, Україна",
    occupation: "Data Scientist",
    viewedProfile: 45468,
    impressions: 19986,
    createdAt: 1288090662,
    updatedAt: 1288090662,
    __v: 0,
  },
  {
    _id: userIds[3],
    firstName: "Юлія",
    lastName: "Шевченко",
    email: "yulia.shevchenko@gmail.com",
    password: "$2b$10$dsasdgsagasda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p6.jpeg",
    friends: [],
    location: "Одеса, Україна",
    occupation: "Маркетолог",
    viewedProfile: 41024,
    impressions: 55316,
    createdAt: 1219214568,
    updatedAt: 1219214568,
    __v: 0,
  },
  {
    _id: userIds[4],
    firstName: "Володимир",
    lastName: "Бондаренко",
    email: "volodymyr.bondarenko@gmail.com",
    password: "$2b$10$dsasdgsagasda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p5.jpeg",
    friends: [],
    location: "Дніпро, Україна",
    occupation: "Кібербезпека",
    viewedProfile: 40212,
    impressions: 7758,
    createdAt: 1493463661,
    updatedAt: 1493463661,
    __v: 0,
  },
  {
    _id: userIds[5],
    firstName: "Катерина",
    lastName: "Ткаченко",
    email: "kateryna.tkachenko@gmail.com",
    password: "$2b$10$dsasdgsagasda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p7.jpeg",
    friends: [],
    location: "Запоріжжя, Україна",
    occupation: "Журналіст",
    viewedProfile: 976,
    impressions: 4658,
    createdAt: 1381326073,
    updatedAt: 1381326073,
    __v: 0,
  },
  {
    _id: userIds[6],
    firstName: "Іван",
    lastName: "Кравченко",
    email: "ivan.kravchenko@gmail.com",
    password: "$2b$10$dsasdgsagasda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p8.jpeg",
    friends: [],
    location: "Вінниця, Україна",
    occupation: "Лікар",
    viewedProfile: 1510,
    impressions: 77579,
    createdAt: 1714704324,
    updatedAt: 1642716557,
    __v: 0,
  },
  {
    _id: userIds[7],
    firstName: "Анастасія",
    lastName: "Лисенко",
    email: "anastasia.lysenko@gmail.com",
    password: "$2b$10$dsasdgsagasda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p9.jpeg",
    friends: [],
    location: "Полтава, Україна",
    occupation: "Студентка",
    viewedProfile: 19420,
    impressions: 82970,
    createdAt: 1369908044,
    updatedAt: 1359322268,
    __v: 0,
  },
];

export const posts = [
  {
    _id: new mongoose.Types.ObjectId(),
    userId: userIds[1],
    firstName: "Марія",
    lastName: "Коваленко",
    location: "Львів, Україна",
    description: "Чудовий день для прогулянки старим містом! #Львів #Україна",
    picturePath: "post1.jpeg",
    userPicturePath: "p3.jpeg",
    likes: new Map([
      [userIds[0], true],
      [userIds[2], true],
      [userIds[3], true],
      [userIds[4], true],
    ]),
    comments: [
      "Чудове фото!",
      "Як красиво!",
      "Обов'язково відвідаю!",
    ],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    userId: userIds[3],
    firstName: "Юлія",
    lastName: "Шевченко",
    location: "Одеса, Україна",
    description: "Морський бриз та чудовий закат на Потьомкінських сходах. #Одеса #Україна",
    picturePath: "post2.jpeg",
    userPicturePath: "p6.jpeg",
    likes: new Map([
      [userIds[7], true],
      [userIds[4], true],
      [userIds[1], true],
      [userIds[2], true],
    ]),
    comments: [
      "Яскравий закат!",
      "Чудовий вид!",
      "Обов'язково відвідаю Одесу!",
      "Красиве місто!",
    ],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    userId: userIds[4],
    firstName: "Володимир",
    lastName: "Бондаренко",
    location: "Дніпро, Україна",
    description: "Новий проект з кібербезпеки. Працюємо над захистом даних українських компаній. #Кібербезпека #Україна",
    picturePath: "post3.jpeg",
    userPicturePath: "p5.jpeg",
    likes: new Map([
      [userIds[1], true],
      [userIds[6], true],
      [userIds[3], true],
      [userIds[5], true],
    ]),
    comments: [
      "Важлива робота!",
      "Успіхів у проекті!",
      "Цікаво дізнатися більше",
      "Гордість за українських спеціалістів!",
    ],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    userId: userIds[5],
    firstName: "Катерина",
    lastName: "Ткаченко",
    location: "Запоріжжя, Україна",
    description: "Репортаж про розвиток IT-індустрії в Запоріжжі. Наші талановиті розробники змінюють майбутнє! #IT #Україна",
    picturePath: "post4.jpeg",
    userPicturePath: "p7.jpeg",
    likes: new Map([
      [userIds[1], true],
      [userIds[6], true],
      [userIds[3], true],
    ]),
    comments: [
      "Чудовий репортаж!",
      "Гордість за нашіх розробників!",
      "Цікаво дізнатися більше про IT в Запоріжжі",
    ],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    userId: userIds[6],
    firstName: "Іван",
    lastName: "Кравченко",
    location: "Вінниця, Україна",
    description: "День в лікарні. Працюємо над покращенням медичної допомоги в регіоні. #Медицина #Україна",
    picturePath: "post5.jpeg",
    userPicturePath: "p8.jpeg",
    likes: new Map([
      [userIds[1], true],
      [userIds[3], true],
      [userIds[5], true],
    ]),
    comments: [
      "Дякую за вашу роботу!",
      "Ви - справжні герої!",
      "Гордість за українську медицину!",
    ],
  },
]; 